default: test

#-------------------------------------------------------------------------------
macros:
  name: NAME_HERE
  user: mbodenhamer
  image: "{{user}}/{{name}}"
  test_image: mbodenhamer/docker-test
  test_image_tag: latest
  repository_name: "docker-{{name}}"
  maintainer_name: Matt Bodenhamer
  maintainer_email: mbodenhamer@mbodenhamer.com
  github_user: "{{user}}"
  branch: master

  docker_version: 17.07.0~ce-0~ubuntu

  testdir: tests # directory where tests are located
  container_workdir: /app

  run_prefix: "docker run --rm -it -v `pwd`:{{container_workdir}}"
  launch_prefix: >
    {{run_prefix}} -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp
  TEST: "{{launch_prefix}} {{test_image}}:{{test_image_tag}}"

#-------------------------------------------------------------------------------
tasks:

  #-----------------------------------------------------------------------------
  # Build

  rsync: "rsync -avz . {{_1}}:{{repository_name}}"

  render_base:
    - yatr --render -i Dockerfile.j2 -o Dockerfile
    - yatr --render -i _README.j2 -o README.md
    - yatr --render -i tests/test_helpers.j2 -o tests/test_helpers.bash
    - yatr --render -i tests/packages.j2 -o tests/packages.bats

  render: render_base

  build_image: "{{TEST}} docker build -t {{image}}:latest ."
  build:
    - render
    - build_image

  #-----------------------------------------------------------------------------
  # Test

  shell: "{{launch_prefix}} {{image}}:latest bash"
  test-shell: "{{TEST}} bash"

  quick-test: "{{TEST}} bats {{testdir}}"
  test:
    - build
    - quick-test

  travis-install:
    - sudo apt-cache madison docker-ce
    - >
      sudo apt-get -o Dpkg::Options::="--force-confnew"
      install -y docker-ce={{docker_version}}
    - docker version

#-------------------------------------------------------------------------------
