macros:
  name: NONE
  user: mbodenhamer
  image: "{{user}}/{{name}}"
  test_image: mbodenhamer/docker-test
  test_image_tag: latest
  repository_name: "docker-{{name}}"

  docker_version: 17.07.0~ce-0~ubuntu

  testdir: tests # directory where tests are located
  container_workdir: /app

  TEST: >
    docker run --rm -it -v `pwd`:{{container_workdir}}
    -v /var/run/docker.sock:/var/run/docker.sock 
    -v /tmp:/tmp {{test_image}}:{{test_image_tag}}

tasks:
  build: "{{TEST}} docker build -t {{image}}:latest ."
  shell: "docker run --rm -it -v `pwd`:/app {{image}} bash"
  test-shell: "{{TEST}} bash"
  quick-test: "{{TEST}} bats {{testdir}}"

  test:
    - build
    - quick-test

  rsync: "rsync -avz . {{_1}}:{{repository_name}}"

  travis-install:
    - sudo apt-cache madison docker-ce
    - 'sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-ce={{docker_version}}'
    - docker version