# Yatrfile for installing a specific docker version from source

#-------------------------------------------------------------------------------
macros:
  docker_arch: x86_64
  docker_version: 17.06.2-ce

  docker_tmpdir: /tmp/install-docker
  docker_tarball: "docker-{{docker_version}}.tgz"
  docker_tarball_url: >
    https://download.docker.com/linux/static/stable/{{docker_arch}}/{{docker_tarball}}

#-------------------------------------------------------------------------------
tasks:
  install-docker-files:
    - "mkdir {{docker_tmpdir}}"
    - "curl -sSL -o {{docker_tmpdir}}/{{docker_tarball}} {{docker_tarball_url}}"
    - "tar zxf {{docker_tmpdir}}/{{docker_tarball}} -C {{docker_tmpdir}}"
    - "mv {{docker_tmpdir}}/docker/* /usr/bin/"
    - "rm -rf {{docker_tmpdir}}"

  add-docker-group: >
    bash -c "if [[ ! $(cat /etc/groups) =~ docker ]]; then addgroup docker; fi"

  start-docker-daemon: "/usr/bin/dockerd &"

  install-docker:
    - install-docker-files
    - add-docker-group
    - start-docker-daemon

#-------------------------------------------------------------------------------
